default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: example
  password: example
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: project_1_development

test:
  <<: *default
  database: project_1_test

production:
  <<: *default
  database: project_1_production
  username: project_1
  password: <%= ENV['PROJECT_1_DATABASE_PASSWORD'] %>
